[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"
[project]
name = "velox-api"  
version = "0.2.2"
description = "A lightweight database-backed task queue and dashboard for Flask APIs"
readme = "README.md"
authors = [{ name = "yaegel" }]
license = "MIT"
requires-python = ">=3.8"
dependencies = [
    "Flask>=2.0.0",
    "psycopg2-binary>=2.9.0"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Framework :: Flask",
]
[project.urls]
Homepage = "https://github.com/yaegel/velox-api"
Issues = "https://github.com/yaegel/velox-api/issues"
[tool.setuptools.packages.find]
where = ["."]
include = ["velox*"]
[tool.setuptools.package-data]
velox = ["templates/*.html"]